n1 = input("digite o primeiro numero: ")
n2 = input("digite o segundo numero: ")
n3 = input("digite o terceiro numero: ") 
n4 = input("digite o quarto numero: ") 
n5 = input("digite o quinto numero: ") 
n6 = input("digite o sexto numero: ")
n7 = input("digite o sétimo numero: ")
n8 = input("digite o oitavo numero: ")
n9 = input("digite o nono numero: ")
n10 = input("digite o décimo numero: ")

lista = [n1, n2, n3, n4, n5, n6, n7, n8, n9, n10]
print("lista normal")
print(lista)
lista.sort()
print("lista em ordem")
print(lista)
lista_ordenada = (set(lista))
print("lista sem repetições")
print(lista_ordenada)
